spring.application.name=portfolio-api

# MySQL Configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DATABASE_URL_DEV}
spring.datasource.username=${DATABASE_USERNAME_DEV}
spring.datasource.password=${DATABASE_PASSWORD_DEV}

# Locale Configuration
spring.web.locale=pt_BR
spring.web.locale-resolver=fixed

# JPA Configuration
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.hibernate.ddl-auto=update

# Disable DevTools restart automatic
spring.devtools.restart.enabled=false
spring.devtools.livereload.enabled=false

# Springdoc OpenAPI 3.1 & Swagger 3 Configuration
springdoc.swagger-ui.path=/docs-portfolio.html
springdoc.api-docs.path=/docs-portfolio
springdoc.packages-to-scan=com.portfolio.portfolio_api.web.controller
